### ISSUE TITLE
Force user to acknowledge mapped points

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/dipnet-fims#2]
When the dataset loads, a bunch of points are put on a map.  We want the user to acknowledge that they have looked at the loaded points.  This is an interface issue.

**Comment by jdeck88** [comment]
is this in dev or master?  are we good to move recent dev branch to master?
John

On Thu, Apr 21, 2016 at 1:59 PM, RJ Ewing notifications@github.com wrote:

> Closed #2 https://github.com/biocodellc/dipnet-fims/issues/2.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/biocodellc/dipnet-fims/issues/2#event-636795657

## 

John Deck
(541) 914-4739

**Comment by rodney757** [comment]
master. the only changes were in dipnet-fims, so it should work just to redeploy dipnet.

don't merge recent biocode-fims-\* develop branches yet
