### ISSUE TITLE
Create a summary stats table for loaded data

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/dipnet-fims#3]
For each expedition, show:
1.  how many loaded records there are
2. how many sequences
3. how many genbank accessions

**Comment by jdeck88** [comment]
Decided on April 16th to create a java class that looks at each expedition in turn and writes these results to a static file, probably JSON.  This can either be referenced on the server or pushed to git.  The expedition manager page will then reference this file directly, response time will be fast.

**Comment by jdeck88** [comment]
merge  #with #5  since we don't really need to call this service... will be replaced by the functionality here.

**Comment by rodney757** [comment]
okay, this is done, except the genbank accessions

**Comment by jdeck88** [comment]
the bulk of this is done, will create a new issue for genbank data
